### ISSUE TITLE
Addon Page: Custom Images

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/site#17]
These can honestly just be screenshots.

Each mod that shows up in the large view needs to have a custom image showing off the content. Then a thumbnail generalizing the content of the mod.

Priority on Assembly Line, ICBM-Classic, and ComeCloser as each of these have a rough looking icon.

**Comment by sfxworks** [comment]
https://github.com/BuiltBrokenModding/site/pull/22/commits/f9cc04e41c6887977e89306475d3fe52b41a119d
