### ISSUE TITLE
Add: Floating text box to bottom of page

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/site#19]
The textbox can be used for general updates and information. Mainly want to use it to ask users visiting the site to help support the site and team. As well to suggest mods for users to try

Should work similiar to the image bellow
![eu-cookie-compliance](https://user-images.githubusercontent.com/1477330/33070152-0f8e3ba8-ce85-11e7-8f2b-b9e80ad73f43.jpg)

**Specification**
Should be out of the way and not block the page
Should show at random times but not to often. No more than twice an hour
Should only show once per page
Should have an exit button
Should populate via JSON so we can control what displays
Should track the last 5 items displayed to avoid repeats

**Use case:**
"If you love our work why not support us on patron [patron logo][patron url]"

**Use case 2:**
"Enjoy our work? Share it with others [share link for site] [twitter share button] [facebook share button... etc]"

**Use case 3:**
"Feel like we could use improvement? Feel free to suggest changes, fixes, features, and content. [Github link]"

**Use case 4:**
[Mod icon] Have you tried [insert mod name as URL] yet?

**Comment by sfxworks** [comment]
Prototype https://github.com/BuiltBrokenModding/site/commit/718cc2a153da6b01a9503fa667a9cbde3b742b5f
