### ISSUE TITLE
Shadow behind text on addon page

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/site#23]
Text on the addon page needs a shadow or background behind it. Most of the text can't be read easily or at all due to the background image.

**Comment by sfxworks** [comment]
![image](https://user-images.githubusercontent.com/5921035/34409498-1cc2aa0e-eb98-11e7-8ded-f653d8ec1c82.png)

**Comment by DarkGuardsman** [comment]
Might need more work as I can't really tell if there is a shadow. Might want to go with a backdrop or different images for some to solve the issue.

The following are hard to read the text:

- [ ] ICBM
- [ ] Bone Torch
- [ ] Helm Bucket
- [ ] Magic Mirror
