### ISSUE TITLE
Download buttons for SBM mods

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/site#24]
SBM mod cards for addon page need a download button. Due to size we can go with a small blue download arrow

**Comment by sfxworks** [comment]
Used a smaller button size instead for consistancy. Good?

**Comment by sfxworks** [comment]
![image](https://user-images.githubusercontent.com/5921035/34409481-02858846-eb98-11e7-97eb-725276129b97.png)
