### ISSUE TITLE
Get news section to match theme color

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/site#31]
Right now news section is bright white. We should get it to match the rest of the site's colors.

![screenshot 2017-12-26 11 17 27](https://user-images.githubusercontent.com/1477330/34360397-7c92b9a8-ea2e-11e7-9d7e-2831edb9d28f.png)

**Comment by sfxworks** [comment]
![image](https://user-images.githubusercontent.com/5921035/34408414-d3099ba8-eb91-11e7-9824-fe5192101e3f.png)
