### ISSUE TITLE
UI & Graphics

### ISSUE THREAD

**Issue by sfxworks** [BuiltBrokenModding/site#9]
Putting this up as an issue per dark's recommendation.
In order to continue with the website, I need some graphics for the UI and elements on the site. I'll make a list here. Just cross them out and post them through a commit once you're done with them.

- [ ] 160x160 image (icon/button version) of all mods

- [ ] 254x1000 image (banner version of all mods) Except the mods that currently exist in [image/banner](https://github.com/BuiltBrokenModding/site/tree/master/img/banner)
- Anything you can think of that you'd like additionally in the banner that meets the 254x1000 requirement

- [x] New background (per Dark's request)

- [x] New Logo (per Dark's request [I believe])

- [ ]  for each (var mod:Mod in BBSModArray) {5 Images, 1 Intro video (like you'd see in steam)

Optional:
- News buttons (png format) with appropriate icons
- Navigation buttons (png format)

**Comment by DarkGuardsman** [comment]
@GreenCafe Make sure to keep the banners simple for the main mod areas. 

For the front page slider use pictures from MC but once again keep it simple. Try to only show the mod in question and minimal interaction with other mods. This way the focus can stay on the mod being shown off and show it in the best light possible. 

@sfxworks Make a master page with all banners on it so people can download the mod advertising banners.

**Comment by dmodoomsirius** [comment]
I assigned @sfxworks as well as this will be a team effort so you both are assigned to this task.

**Comment by sfxworks** [comment]
That was already a given but I gotcha. I can't do much because I can't really run modded Minecraft on this mini laptop though.

Also, probably going to do webp format. Read more on it here. https://developers.google.com/speed/webp/

**Comment by DarkGuardsman** [comment]
I have not heard of that format but as long as it works without extra client-side code then it will be fine.

**Comment by sfxworks** [comment]
It will fall back to pngs if the client doesn't support it. We will be good. This is mainly a benefit for our Google chrome users as they already natively support WebP.

**Comment by DarkGuardsman** [comment]
Closing due to being outdated
